version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    volumes:
      - ./client:/client

  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    ports:
      - '4444:4444'
    volumes:
      - ./account:/account
